# Generated by Django 3.2 on 2021-04-17 17:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(help_text='A code that uniquely identifies this department.', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(help_text='A human friendly name.', max_length=80, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('types', utilities.ChoiceArrayField(base_field=models.CharField(choices=[('LECTURE', 'Lecture'), ('DIRECTED', 'Directed studies'), ('PRACTICAL', 'Practical work')], max_length=15), default=list, size=None, verbose_name='types')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.CharField(help_text='A code that uniquely identifies this section.', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('number_of_groups', models.PositiveSmallIntegerField(help_text='The number of groups this section is divided into.', verbose_name='number of groups')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section', verbose_name='section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Teacher-Section',
                'verbose_name_plural': 'Teachers-Sections',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('code', models.CharField(help_text='A code that uniquely identifies this specialty.', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(help_text='A human friendly name.', max_length=80, verbose_name='name')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.specialty', verbose_name='specialty'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('module_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('DIRECTED', 'Directed studies'), ('PRACTICAL', 'Practical work')], max_length=15, verbose_name='module type')),
                ('concerned_groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.module', verbose_name='module')),
                ('teacher_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.teachersection', verbose_name='teacher-section')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='teachersection',
            constraint=models.UniqueConstraint(fields=('teacher', 'section'), name='unique_teachers_section'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('teacher_section', 'module', 'module_type'), name='unique_assignment'),
        ),
    ]
