# Generated by Django 3.2 on 2021-04-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(help_text='A code that uniquely identifies this section.', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(help_text='A human friendly name.', max_length=80, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('code', models.CharField(help_text='A code that uniquely identifies this specialty.', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(help_text='A human friendly name.', max_length=80, verbose_name='name')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.CharField(help_text='A code that uniquely identifies this section.', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('number_of_groups', models.IntegerField(help_text='The number of groups this section is divided into.', verbose_name='number of groups')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.specialty', verbose_name='specialty')),
            ],
        ),
    ]
