# Generated by Django 3.2 on 2021-04-18 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='concerned_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None, verbose_name='concerned groups'),
        ),
    ]
