# Generated by Django 3.2 on 2021-04-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_assignment_concerned_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='Department',
        ),
        migrations.AddField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(default='INFO', on_delete=django.db.models.deletion.CASCADE, to='Management.department', verbose_name='department'),
            preserve_default=False,
        ),
    ]
