# Generated by Django 3.2 on 2021-04-16 16:27

from django.db import migrations, models
import utilities


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20210416_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('types', utilities.ChoiceArrayField(base_field=models.CharField(choices=[('LECTURE', 'Lecture'), ('DIRECTED', 'Directed studies'), ('PRACTICAL', 'Practical work')], max_length=15), default=list, size=None, verbose_name='types')),
            ],
        ),
    ]
