# Generated by Django 3.2 on 2021-04-16 17:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210416_1821'),
        ('Management', '0003_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section', verbose_name='section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Teacher-Section',
                'verbose_name_plural': 'Teachers-Sections',
            },
        ),
        migrations.CreateModel(
            name='Assignement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('module_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('DIRECTED', 'Directed studies'), ('PRACTICAL', 'Practical work')], max_length=15, verbose_name='module type')),
                ('concerned_groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.module', verbose_name='module')),
                ('teacher_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.teachersection', verbose_name='teacher-section')),
            ],
            options={
                'verbose_name': 'Assignement',
                'verbose_name_plural': 'Assignements',
            },
        ),
        migrations.AddConstraint(
            model_name='assignement',
            constraint=models.UniqueConstraint(fields=('teacher_section', 'module', 'module_type'), name='unique_assignement'),
        ),
    ]
