# Generated by Django 3.2 on 2021-05-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210424_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Module-Section',
                'verbose_name_plural': 'Modules-Sections',
            },
        ),
        migrations.RemoveConstraint(
            model_name='teachersection',
            name='unique_teachers_section',
        ),
        migrations.AddConstraint(
            model_name='teachersection',
            constraint=models.UniqueConstraint(fields=('teacher', 'section'), name='unique_modules_section'),
        ),
        migrations.AddField(
            model_name='modulesection',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='modulesection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='section',
            name='modules',
            field=models.ManyToManyField(through='Management.ModuleSection', to='Management.Module', verbose_name='modules'),
        ),
        migrations.AddConstraint(
            model_name='modulesection',
            constraint=models.UniqueConstraint(fields=('module', 'section'), name='unique_teachers_section'),
        ),
    ]
