# Generated by Django 3.2 on 2021-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20210416_1821'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teachersection',
            constraint=models.UniqueConstraint(fields=('teacher', 'section'), name='unique_teachers_section'),
        ),
    ]
