# Generated by Django 3.2 on 2021-04-17 15:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('concerned_groups', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('day', models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=15, verbose_name='day')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('meeting_link', models.CharField(max_length=400, verbose_name='meeting link')),
                ('meeting_number', models.CharField(blank=True, max_length=50, verbose_name='meeting number')),
                ('meeting_password', models.CharField(blank=True, max_length=50, verbose_name='meeting password')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.assignment', verbose_name='assignment')),
            ],
        ),
    ]
