# Generated by Django 3.2 on 2021-05-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0002_auto_20210512_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('start_time',), 'verbose_name': 'Session  ', 'verbose_name_plural': 'Sessions'},
        ),
    ]
