# Generated by Django 3.2 on 2021-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0004_alter_sessionhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionhistory',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='action date'),
        ),
    ]
