# Generated by Django 3.2 on 2021-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0006_alter_sessionhistory_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday')], verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='day',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday')], verbose_name='day'),
        ),
    ]
