# Generated by Django 3.2 on 2021-04-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sections',
            field=models.ManyToManyField(to='Management.Section', verbose_name='sections'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section', verbose_name='section'),
        ),
    ]
