# Generated by Django 3.2 on 2021-04-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.user', verbose_name='user')),
                ('grade', models.CharField(choices=[('MAB', 'MAB'), ('MAA', 'MAA'), ('MCB', 'MCB'), ('MCA', 'MCA'), ('PR', 'Pr'), ('DOC', 'Doc')], max_length=10, verbose_name='grade')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section', verbose_name='section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.teacher', verbose_name='teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='sections',
            field=models.ManyToManyField(through='Accounts.TeacherSection', to='Management.Section', verbose_name='sections'),
        ),
    ]
