# Generated by Django 3.2 on 2021-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.SmallIntegerField(default=1, verbose_name='group'),
            preserve_default=False,
        ),
    ]
