# Generated by Django 3.2 on 2021-04-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20210416_1621'),
        ('Accounts', '0003_auto_20210416_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.user', verbose_name='user')),
                ('registration_number', models.CharField(max_length=20, verbose_name='registration number')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.section', verbose_name='section')),
            ],
        ),
    ]
