# Generated by Django 3.2 on 2021-04-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teachersection',
            name='teacher',
        ),
    ]
