# Generated by Django 3.2 on 2021-05-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210424_1857'),
        ('Accounts', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default='INFO', on_delete=django.db.models.deletion.CASCADE, to='Management.department', verbose_name='department'),
            preserve_default=False,
        ),
    ]
