# Generated by Django 3.2 on 2021-04-17 17:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('concerned_groups', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('comment', models.TextField(verbose_name='comment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.assignment', verbose_name='assignment')),
            ],
        ),
    ]
