# Generated by Django 3.2 on 2021-04-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
    ]
