# Generated by Django 3.2 on 2021-05-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_time',
            field=models.TimeField(default='10:00', verbose_name='due time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
    ]
