# Generated by Django 3.2 on 2021-05-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0003_auto_20210522_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('due_date', 'due_time'), 'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
    ]
