# Generated by Django 3.2 on 2021-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworks', '0003_auto_20210418_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
